name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
      - run: yarn
      - run: yarn test
      - run: yarn lint
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: "swanky-plugin-phala"
          path: |
            dist/
            package.json
            README.md
